packages:
  - apps/*
  - packages/*
catalog:
  '@next/eslint-plugin-next': ^15.2.1
  '@radix-ui/react-accordion': ^1.2.3
  '@radix-ui/react-slot': ^1.1.2
  '@tailwindcss/postcss': ^4.0.10
  '@types/bcryptjs': ^2.4.6
  '@types/node': ^22.13.9
  babel-plugin-react-compiler: 19.0.0-beta-40c6c23-20250301
  bcrypt-ts: ^5.0.2
  bcryptjs: ^2.4.3
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  concurrently: ^8.2.0
  eslint: ^9.21.0
  eslint-config-prettier: ^10.0.2
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.4
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.4.4
  globals: ^16.0.0
  lucide-react: ^0.477.0
  next: ^15.2.1
  next-auth: 5.0.0-beta.25
  '@next/bundle-analyzer': ^14.1.0
  postcss: ^8.5.3
  prettier: ^3.5.3
  react: ^19.0.0
  react-dom: ^19.0.0
  rimraf: ^5.0.5
  server-only: ^0.0.1
  tailwind-merge: ^3.0.2
  tailwindcss: ^4.0.10
  tailwindcss-animate: ^1.0.7
  tsx: ^4.19.3
  turbo: ^2.4.4
  typescript-eslint: ^8.26.0
  zod: ^3.24.2
  typescript: '^5.8.2'
  '@types/react': ^19.0.10
  '@types/react-dom': ^19.0.4
  tsup: ^8.0.2
  prisma: ^6.4.1
  '@prisma/client': ^6.4.1
  '@auth/prisma-adapter': ^2.7.4
  eslint-plugin-import: ^2.31.0
  eslint-plugin-prettier: ^5.2.3
  eslint-plugin-simple-import-sort: ^12.1.1
  '@typescript-eslint/eslint-plugin': ^8.26.1
  '@typescript-eslint/parser': ^8.26.0
  dotenv: ^16.4.1
